param()

$token = $env:GITHUB_TOKEN
$apkPath = "d:\project\photoRoulette\build\outputs\apk\release\photoRoulette-release.apk"
$owner = "JaneJane123654"
$repo = "photoRoulette"
$tagName = "v1.1.3"

Write-Host "Creating GitHub Release for $tagName..."

# 创建 Release
$releaseBody = "Automated Release v1.1.3`n`nGenerated by auto-release workflow"
$releaseUrl = "https://api.github.com/repos/$owner/$repo/releases"

$releaseData = @{
    tag_name = $tagName
    name = "Release $tagName"
    body = $releaseBody
    draft = $false
    prerelease = $false
} | ConvertTo-Json

Write-Host "Release API URL: $releaseUrl"

try {
    $releaseResponse = Invoke-RestMethod -Uri $releaseUrl `
        -Method POST `
        -Headers @{
            "Authorization" = "token $token"
            "Accept" = "application/vnd.github.v3+json"
        } `
        -Body $releaseData `
        -ContentType "application/json" `
        -ErrorAction Stop

    Write-Host "Release created successfully!"
    Write-Host "Release URL: $($releaseResponse.html_url)"
    
    $uploadUrl = $releaseResponse.upload_url -replace '\{\?name,label\}', ''
    $apkFileName = (Get-Item $apkPath).Name
    $uploadUri = "$uploadUrl`?name=$apkFileName"
    
    Write-Host "Uploading APK: $apkFileName"
    $apkBytes = [System.IO.File]::ReadAllBytes($apkPath)
    
    $uploadResponse = Invoke-RestMethod -Uri $uploadUri `
        -Method POST `
        -Headers @{
            "Authorization" = "token $token"
            "Accept" = "application/vnd.github.v3+json"
            "Content-Type" = "application/octet-stream"
        } `
        -Body $apkBytes `
        -ErrorAction Stop
    
    Write-Host "APK uploaded successfully!"
    Write-Host "Download URL: $($uploadResponse.browser_download_url)"
    
}
catch {
    Write-Host "Error: $_"
    exit 1
}
